server:
  shutdown: graceful
  port: 8082

spring:
  config:
    activate:
      on-profile: default
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:mysql://localhost:3307/cmsorder?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  redis:
    host: localhost
    port: 6379

feign:
  okhttp:
    enabled: true